### ISSUE TITLE
用androidannotations无法跳转

### ISSUE THREAD

**Issue by for7GG** [ssseasonnn/RxRouter#2]
类库地址：https://github.com/androidannotations/androidannotations/wiki/AvailableAnnotations
使用androidannotations会生成当前类名加_的类，无法实现url跳转，可以加上对androidannotations的支持吗？
类似这样：
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.TYPE)
public @interface Url {
    String value();
    boolean isAA() default false;
}

**Comment by for7GG** [comment]
![1](https://user-images.githubusercontent.com/10189846/38786186-e555bbbc-4158-11e8-9b35-7ddfcdf7d4b6.png)
![2](https://user-images.githubusercontent.com/10189846/38786187-e5dc8f52-4158-11e8-9202-23d51f2ab584.png)
![3](https://user-images.githubusercontent.com/10189846/38786188-e627f212-4158-11e8-89b8-b199464c1afe.png)
这目前是我的逻辑，希望添加到您的项目中去

**Comment by ssseasonnn** [comment]
好的

**Comment by ssseasonnn** [comment]
现在应该可以了，刚才发布了新版本，你再试下

**Comment by for7GG** [comment]
@ssseasonnn 谢谢，可以了
