### ISSUE TITLE
打开的页面关闭时, 会再次打开

### ISSUE THREAD

**Issue by WangYng** [ssseasonnn/RxRouter#5]
在三星S8上面, 当RouteAcitivty打开一个新的页面时, 紧接着会触发onRestoreInstanceState函数. 这时RouteActivity会被缓存起来. 当新打开的页面关闭时, 退回到RouteAcitivity, 会再次触发onCreate函数. Bug产生了. 
<img width="721" alt="38a9773c-d525-4f74-9327-1cb0fa6d5658" src="https://user-images.githubusercontent.com/7321087/41099410-ff904554-6a90-11e8-8501-c55224c3bf82.png">
<img width="777" alt="d37fbe2c-bfea-4998-963f-401ba9f457be" src="https://user-images.githubusercontent.com/7321087/41099415-050b8caa-6a91-11e8-9dfd-37a90bae8214.png">

**Comment by WangYng** [comment]
原来是测试的兄弟打开了手机的"严格模式"😂

**Comment by ssseasonnn** [comment]
😂
